name: "[op-rbuilder] Checks"

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: warp-ubuntu-latest-x64-16x
    env:
      # Set features for the Makefile
      FEATURES: ${{ matrix.features }}
    strategy:
      matrix:
        toolchain:
          - nightly-2026-02-21
        features:
          - ""

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # https://github.com/dtolnay/rust-toolchain
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "rustfmt,clippy"

      # https://github.com/swatinem/rust-cache
      - name: Run Swatinem/rust-cache@v2
        if: ${{ !env.ACT }}
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      # https://github.com/Mozilla-Actions/sccache-action
      - name: Run sccache-action
        if: ${{ !env.ACT }}
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Set sccache env vars
        if: ${{ !env.ACT }}
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Install Foundry toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install native dependencies
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev clang libclang-dev llvm build-essential pkg-config libtss2-dev

      - name: Compile tester
        run: make tester

      - name: Compile op-rbuilder
        run: cargo build -p op-rbuilder --bin op-rbuilder

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          TESTS_TEMP_DIR: ${{ github.workspace }}

      - name: Run op-rbuilder with builder-playground
        uses: flashbots/builder-playground-action@v1
        with:
          version: v0.3.2-alpha.4
          recipe: playground.yaml
          args: --skip-setup

      - name: Send test tx to op-rbuilder
        run: builder-playground test http://localhost:2222 --timeout 30s --retries 10
